package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA



/**
 * TblAsignacionSolicitud generated by hbm2java
 */
public class TblAsignacionSolicitud  implements java.io.Serializable {


     private int idAsignacionSolicitud;
     private TblSolicitud tblSolicitud;
     private TblUsuario tblUsuario;

    public TblAsignacionSolicitud() {
    }

	
    public TblAsignacionSolicitud(int idAsignacionSolicitud) {
        this.idAsignacionSolicitud = idAsignacionSolicitud;
    }
    public TblAsignacionSolicitud(int idAsignacionSolicitud, TblSolicitud tblSolicitud, TblUsuario tblUsuario) {
       this.idAsignacionSolicitud = idAsignacionSolicitud;
       this.tblSolicitud = tblSolicitud;
       this.tblUsuario = tblUsuario;
    }
   
    public int getIdAsignacionSolicitud() {
        return this.idAsignacionSolicitud;
    }
    
    public void setIdAsignacionSolicitud(int idAsignacionSolicitud) {
        this.idAsignacionSolicitud = idAsignacionSolicitud;
    }
    public TblSolicitud getTblSolicitud() {
        return this.tblSolicitud;
    }
    
    public void setTblSolicitud(TblSolicitud tblSolicitud) {
        this.tblSolicitud = tblSolicitud;
    }
    public TblUsuario getTblUsuario() {
        return this.tblUsuario;
    }
    
    public void setTblUsuario(TblUsuario tblUsuario) {
        this.tblUsuario = tblUsuario;
    }




}


