package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * TblAsignacionSolicitud generated by hbm2java
 */
public class TblAsignacionSolicitud  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_asignacion_solicitud")    
     private Long idAsignacionSolicitud;
     private TblSolicitud tblSolicitud;
     private TblUsuario tblUsuario;

    public TblAsignacionSolicitud() {
    }

	
    public TblAsignacionSolicitud(Long idAsignacionSolicitud) {
        this.idAsignacionSolicitud = idAsignacionSolicitud;
    }
    public TblAsignacionSolicitud(Long idAsignacionSolicitud, TblSolicitud tblSolicitud, TblUsuario tblUsuario) {
       this.idAsignacionSolicitud = idAsignacionSolicitud;
       this.tblSolicitud = tblSolicitud;
       this.tblUsuario = tblUsuario;
    }
   
    public Long getIdAsignacionSolicitud() {
        return this.idAsignacionSolicitud;
    }
    
    public void setIdAsignacionSolicitud(Long idAsignacionSolicitud) {
        this.idAsignacionSolicitud = idAsignacionSolicitud;
    }
    public TblSolicitud getTblSolicitud() {
        return this.tblSolicitud;
    }
    
    public void setTblSolicitud(TblSolicitud tblSolicitud) {
        this.tblSolicitud = tblSolicitud;
    }
    public TblUsuario getTblUsuario() {
        return this.tblUsuario;
    }
    
    public void setTblUsuario(TblUsuario tblUsuario) {
        this.tblUsuario = tblUsuario;
    }




}


