package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * TblClima generated by hbm2java
 */
public class TblClima  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_clima")   
     private Long idClima;
     private String nombreClima;

    public TblClima() {
    }

	
    public TblClima(Long idClima) {
        this.idClima = idClima;
    }
    public TblClima(Long idClima, String nombreClima) {
       this.idClima = idClima;
       this.nombreClima = nombreClima;
    }
   
    public Long getIdClima() {
        return this.idClima;
    }
    
    public void setIdClima(Long idClima) {
        this.idClima = idClima;
    }
    public String getNombreClima() {
        return this.nombreClima;
    }
    
    public void setNombreClima(String nombreClima) {
        this.nombreClima = nombreClima;
    }




}


