package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblCultivo generated by hbm2java
 */
public class TblCultivo  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_cultivo") 
     private Long idCultivo;
     private TblTecnicaCultivo tblTecnicaCultivo;
     private TblVariedad tblVariedad;
     private TblEstadoProduccion tblEstadoProduccion;
     private String nombreCultivo;
     private String extensionCultivo;
     private Long idClima;
     private String edadCultivo;
     private Set tblSolicituds = new HashSet(0);

    public TblCultivo() {
    }

	
    public TblCultivo(Long idCultivo, String nombreCultivo) {
        this.idCultivo = idCultivo;
        this.nombreCultivo = nombreCultivo;
    }
    public TblCultivo(Long idCultivo, TblTecnicaCultivo tblTecnicaCultivo, TblVariedad tblVariedad, TblEstadoProduccion tblEstadoProduccion, String nombreCultivo, String extensionCultivo, Long idClima, String edadCultivo, Set tblSolicituds) {
       this.idCultivo = idCultivo;
       this.tblTecnicaCultivo = tblTecnicaCultivo;
       this.tblVariedad = tblVariedad;
       this.tblEstadoProduccion = tblEstadoProduccion;
       this.nombreCultivo = nombreCultivo;
       this.extensionCultivo = extensionCultivo;
       this.idClima = idClima;
       this.edadCultivo = edadCultivo;
       this.tblSolicituds = tblSolicituds;
    }
   
    public Long getIdCultivo() {
        return this.idCultivo;
    }
    
    public void setIdCultivo(Long idCultivo) {
        this.idCultivo = idCultivo;
    }
    public TblTecnicaCultivo getTblTecnicaCultivo() {
        return this.tblTecnicaCultivo;
    }
    
    public void setTblTecnicaCultivo(TblTecnicaCultivo tblTecnicaCultivo) {
        this.tblTecnicaCultivo = tblTecnicaCultivo;
    }
    public TblVariedad getTblVariedad() {
        return this.tblVariedad;
    }
    
    public void setTblVariedad(TblVariedad tblVariedad) {
        this.tblVariedad = tblVariedad;
    }
    public TblEstadoProduccion getTblEstadoProduccion() {
        return this.tblEstadoProduccion;
    }
    
    public void setTblEstadoProduccion(TblEstadoProduccion tblEstadoProduccion) {
        this.tblEstadoProduccion = tblEstadoProduccion;
    }
    public String getNombreCultivo() {
        return this.nombreCultivo;
    }
    
    public void setNombreCultivo(String nombreCultivo) {
        this.nombreCultivo = nombreCultivo;
    }
    public String getExtensionCultivo() {
        return this.extensionCultivo;
    }
    
    public void setExtensionCultivo(String extensionCultivo) {
        this.extensionCultivo = extensionCultivo;
    }
    public Long getIdClima() {
        return this.idClima;
    }
    
    public void setIdClima(Long idClima) {
        this.idClima = idClima;
    }
    public String getEdadCultivo() {
        return this.edadCultivo;
    }
    
    public void setEdadCultivo(String edadCultivo) {
        this.edadCultivo = edadCultivo;
    }
    public Set getTblSolicituds() {
        return this.tblSolicituds;
    }
    
    public void setTblSolicituds(Set tblSolicituds) {
        this.tblSolicituds = tblSolicituds;
    }




}


