package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblCiudad generated by hbm2java
 */
public class TblCiudad  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_ciudad")   
     private Long idCiudad;
     private TblDepartamento tblDepartamento;
     private String nombreCiudad;
     private Set tblDetalleUsuarios = new HashSet(0);

    public TblCiudad() {
    }

	
    public TblCiudad(Long idCiudad) {
        this.idCiudad = idCiudad;
    }
    public TblCiudad(Long idCiudad, TblDepartamento tblDepartamento, String nombreCiudad, Set tblDetalleUsuarios) {
       this.idCiudad = idCiudad;
       this.tblDepartamento = tblDepartamento;
       this.nombreCiudad = nombreCiudad;
       this.tblDetalleUsuarios = tblDetalleUsuarios;
    }
   
    public Long getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(long idCiudad) {
        this.idCiudad = idCiudad;
    }
    public TblDepartamento getTblDepartamento() {
        return this.tblDepartamento;
    }
    
    public void setTblDepartamento(TblDepartamento tblDepartamento) {
        this.tblDepartamento = tblDepartamento;
    }
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }
    public Set getTblDetalleUsuarios() {
        return this.tblDetalleUsuarios;
    }
    
    public void setTblDetalleUsuarios(Set tblDetalleUsuarios) {
        this.tblDetalleUsuarios = tblDetalleUsuarios;
    }




}


