package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * TblContacto generated by hbm2java
 */
public class TblContacto  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_contacto")   
     private Long idContacto;
     private TblTipoContacto tblTipoContacto;
     private TblSolicitante tblSolicitante;
     private String contacto;

    public TblContacto() {
    }

	
    public TblContacto(Long idContacto) {
        this.idContacto = idContacto;
    }
    public TblContacto(Long idContacto, TblTipoContacto tblTipoContacto, TblSolicitante tblSolicitante, String contacto) {
       this.idContacto = idContacto;
       this.tblTipoContacto = tblTipoContacto;
       this.tblSolicitante = tblSolicitante;
       this.contacto = contacto;
    }
   
    public Long getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(Long idContacto) {
        this.idContacto = idContacto;
    }
    public TblTipoContacto getTblTipoContacto() {
        return this.tblTipoContacto;
    }
    
    public void setTblTipoContacto(TblTipoContacto tblTipoContacto) {
        this.tblTipoContacto = tblTipoContacto;
    }
    public TblSolicitante getTblSolicitante() {
        return this.tblSolicitante;
    }
    
    public void setTblSolicitante(TblSolicitante tblSolicitante) {
        this.tblSolicitante = tblSolicitante;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }




}


