package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblDiagnosticoCaracteristica generated by hbm2java
 */
public class TblDiagnosticoCaracteristica implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_diagnostico_caracteristica")
    private Long idDiagnosticoCaracteristica;
    private TblDiagnostico tblDiagnosticoByIdDiagnostico;
    private TblDiagnostico tblDiagnosticoByIdDiagnosticoRelacionado;
    private String mapPie;
    private String mapSintoma;

    public TblDiagnosticoCaracteristica() {
    }

    public TblDiagnosticoCaracteristica(Long idDiagnosticoCaracteristica) {
        this.idDiagnosticoCaracteristica = idDiagnosticoCaracteristica;
    }

    public TblDiagnosticoCaracteristica(Long idDiagnosticoCaracteristica, TblDiagnostico tblDiagnosticoByIdDiagnostico, TblDiagnostico tblDiagnosticoByIdDiagnosticoRelacionado) {
        this.idDiagnosticoCaracteristica = idDiagnosticoCaracteristica;
        this.tblDiagnosticoByIdDiagnostico = tblDiagnosticoByIdDiagnostico;
        this.tblDiagnosticoByIdDiagnosticoRelacionado = tblDiagnosticoByIdDiagnosticoRelacionado;
    }

    public Long getIdDiagnosticoCaracteristica() {
        return this.idDiagnosticoCaracteristica;
    }

    public void setIdDiagnosticoCaracteristica(Long idDiagnosticoCaracteristica) {
        this.idDiagnosticoCaracteristica = idDiagnosticoCaracteristica;
    }

    public TblDiagnostico getTblDiagnosticoByIdDiagnostico() {
        return this.tblDiagnosticoByIdDiagnostico;
    }

    public void setTblDiagnosticoByIdDiagnostico(TblDiagnostico tblDiagnosticoByIdDiagnostico) {
        this.tblDiagnosticoByIdDiagnostico = tblDiagnosticoByIdDiagnostico;
    }

    public TblDiagnostico getTblDiagnosticoByIdDiagnosticoRelacionado() {
        return this.tblDiagnosticoByIdDiagnosticoRelacionado;
    }

    public void setTblDiagnosticoByIdDiagnosticoRelacionado(TblDiagnostico tblDiagnosticoByIdDiagnosticoRelacionado) {
        this.tblDiagnosticoByIdDiagnosticoRelacionado = tblDiagnosticoByIdDiagnosticoRelacionado;
    }

    public String getMapPie() {
        return mapPie;
    }

    public void setMapPie(String mapPie) {
        this.mapPie = mapPie;
    }

    public String getMapSintoma() {
        return mapSintoma;
    }

    public void setMapSintoma(String mapSintoma) {
        this.mapSintoma = mapSintoma;
    }
    
    
    
}
