package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA



/**
 * TblDiagnosticoImagen generated by hbm2java
 */
public class TblDiagnosticoImagen  implements java.io.Serializable {


     private int idDiagnosticoImagen;
     private TblDiagnostico tblDiagnosticoByIdDiagnostico;
     private TblDiagnostico tblDiagnosticoByIdDiagnosticoRelacionado;

    public TblDiagnosticoImagen() {
    }

	
    public TblDiagnosticoImagen(int idDiagnosticoImagen) {
        this.idDiagnosticoImagen = idDiagnosticoImagen;
    }
    public TblDiagnosticoImagen(int idDiagnosticoImagen, TblDiagnostico tblDiagnosticoByIdDiagnostico, TblDiagnostico tblDiagnosticoByIdDiagnosticoRelacionado) {
       this.idDiagnosticoImagen = idDiagnosticoImagen;
       this.tblDiagnosticoByIdDiagnostico = tblDiagnosticoByIdDiagnostico;
       this.tblDiagnosticoByIdDiagnosticoRelacionado = tblDiagnosticoByIdDiagnosticoRelacionado;
    }
   
    public int getIdDiagnosticoImagen() {
        return this.idDiagnosticoImagen;
    }
    
    public void setIdDiagnosticoImagen(int idDiagnosticoImagen) {
        this.idDiagnosticoImagen = idDiagnosticoImagen;
    }
    public TblDiagnostico getTblDiagnosticoByIdDiagnostico() {
        return this.tblDiagnosticoByIdDiagnostico;
    }
    
    public void setTblDiagnosticoByIdDiagnostico(TblDiagnostico tblDiagnosticoByIdDiagnostico) {
        this.tblDiagnosticoByIdDiagnostico = tblDiagnosticoByIdDiagnostico;
    }
    public TblDiagnostico getTblDiagnosticoByIdDiagnosticoRelacionado() {
        return this.tblDiagnosticoByIdDiagnosticoRelacionado;
    }
    
    public void setTblDiagnosticoByIdDiagnosticoRelacionado(TblDiagnostico tblDiagnosticoByIdDiagnosticoRelacionado) {
        this.tblDiagnosticoByIdDiagnosticoRelacionado = tblDiagnosticoByIdDiagnosticoRelacionado;
    }




}


