package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA



/**
 * TblDetalleUsuario generated by hbm2java
 */
public class TblDetalleUsuario  implements java.io.Serializable {


     private int idDetalleUsuario;
     private TblTipoDocumento tblTipoDocumento;
     private TblUsuario tblUsuario;
     private TblCiudad tblCiudad;
     private String nombreUsuario;
     private String apellidoUsuario;
     private String numeroDocumento;
     private String direccion;
     private String email;
     private Integer idContacto;

    public TblDetalleUsuario() {
    }

	
    public TblDetalleUsuario(int idDetalleUsuario) {
        this.idDetalleUsuario = idDetalleUsuario;
    }
    public TblDetalleUsuario(int idDetalleUsuario, TblTipoDocumento tblTipoDocumento, TblUsuario tblUsuario, TblCiudad tblCiudad, String nombreUsuario, String apellidoUsuario, String numeroDocumento, String direccion, String email, Integer idContacto) {
       this.idDetalleUsuario = idDetalleUsuario;
       this.tblTipoDocumento = tblTipoDocumento;
       this.tblUsuario = tblUsuario;
       this.tblCiudad = tblCiudad;
       this.nombreUsuario = nombreUsuario;
       this.apellidoUsuario = apellidoUsuario;
       this.numeroDocumento = numeroDocumento;
       this.direccion = direccion;
       this.email = email;
       this.idContacto = idContacto;
    }
   
    public int getIdDetalleUsuario() {
        return this.idDetalleUsuario;
    }
    
    public void setIdDetalleUsuario(int idDetalleUsuario) {
        this.idDetalleUsuario = idDetalleUsuario;
    }
    public TblTipoDocumento getTblTipoDocumento() {
        return this.tblTipoDocumento;
    }
    
    public void setTblTipoDocumento(TblTipoDocumento tblTipoDocumento) {
        this.tblTipoDocumento = tblTipoDocumento;
    }
    public TblUsuario getTblUsuario() {
        return this.tblUsuario;
    }
    
    public void setTblUsuario(TblUsuario tblUsuario) {
        this.tblUsuario = tblUsuario;
    }
    public TblCiudad getTblCiudad() {
        return this.tblCiudad;
    }
    
    public void setTblCiudad(TblCiudad tblCiudad) {
        this.tblCiudad = tblCiudad;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getApellidoUsuario() {
        return this.apellidoUsuario;
    }
    
    public void setApellidoUsuario(String apellidoUsuario) {
        this.apellidoUsuario = apellidoUsuario;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(Integer idContacto) {
        this.idContacto = idContacto;
    }




}


