package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA



/**
 * TblDiagnosticoCaracteristica generated by hbm2java
 */
public class TblDiagnosticoCaracteristica  implements java.io.Serializable {


     private int idDiagnosticoCaracteristica;
     private TblDiagnostico tblDiagnosticoByIdDiagnostico;
     private TblDiagnostico tblDiagnosticoByIdDiagnosticoRelacionado;

    public TblDiagnosticoCaracteristica() {
    }

	
    public TblDiagnosticoCaracteristica(int idDiagnosticoCaracteristica) {
        this.idDiagnosticoCaracteristica = idDiagnosticoCaracteristica;
    }
    public TblDiagnosticoCaracteristica(int idDiagnosticoCaracteristica, TblDiagnostico tblDiagnosticoByIdDiagnostico, TblDiagnostico tblDiagnosticoByIdDiagnosticoRelacionado) {
       this.idDiagnosticoCaracteristica = idDiagnosticoCaracteristica;
       this.tblDiagnosticoByIdDiagnostico = tblDiagnosticoByIdDiagnostico;
       this.tblDiagnosticoByIdDiagnosticoRelacionado = tblDiagnosticoByIdDiagnosticoRelacionado;
    }
   
    public int getIdDiagnosticoCaracteristica() {
        return this.idDiagnosticoCaracteristica;
    }
    
    public void setIdDiagnosticoCaracteristica(int idDiagnosticoCaracteristica) {
        this.idDiagnosticoCaracteristica = idDiagnosticoCaracteristica;
    }
    public TblDiagnostico getTblDiagnosticoByIdDiagnostico() {
        return this.tblDiagnosticoByIdDiagnostico;
    }
    
    public void setTblDiagnosticoByIdDiagnostico(TblDiagnostico tblDiagnosticoByIdDiagnostico) {
        this.tblDiagnosticoByIdDiagnostico = tblDiagnosticoByIdDiagnostico;
    }
    public TblDiagnostico getTblDiagnosticoByIdDiagnosticoRelacionado() {
        return this.tblDiagnosticoByIdDiagnosticoRelacionado;
    }
    
    public void setTblDiagnosticoByIdDiagnosticoRelacionado(TblDiagnostico tblDiagnosticoByIdDiagnosticoRelacionado) {
        this.tblDiagnosticoByIdDiagnosticoRelacionado = tblDiagnosticoByIdDiagnosticoRelacionado;
    }




}


