package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblDepartamento generated by hbm2java
 */
public class TblDepartamento  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_departamento")
     private Long idDepartamento;
     private String nombreDepartamento;
     private Set tblVeredas = new HashSet(0);
     private Set tblCiudads = new HashSet(0);

    public TblDepartamento() {
    }

	
    public TblDepartamento(Long idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public TblDepartamento(Long idDepartamento, String nombreDepartamento, Set tblVeredas, Set tblCiudads) {
       this.idDepartamento = idDepartamento;
       this.nombreDepartamento = nombreDepartamento;
       this.tblVeredas = tblVeredas;
       this.tblCiudads = tblCiudads;
    }
   
    public Long getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Long idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set getTblVeredas() {
        return this.tblVeredas;
    }
    
    public void setTblVeredas(Set tblVeredas) {
        this.tblVeredas = tblVeredas;
    }
    public Set getTblCiudads() {
        return this.tblCiudads;
    }
    
    public void setTblCiudads(Set tblCiudads) {
        this.tblCiudads = tblCiudads;
    }




}


