package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TblEtapa generated by hbm2java
 */
public class TblEtapa  implements java.io.Serializable {


     private int idEtapa;
     private String descripcionEtapa;
     private Set tblSolicituds = new HashSet(0);

    public TblEtapa() {
    }

	
    public TblEtapa(int idEtapa) {
        this.idEtapa = idEtapa;
    }
    public TblEtapa(int idEtapa, String descripcionEtapa, Set tblSolicituds) {
       this.idEtapa = idEtapa;
       this.descripcionEtapa = descripcionEtapa;
       this.tblSolicituds = tblSolicituds;
    }
   
    public int getIdEtapa() {
        return this.idEtapa;
    }
    
    public void setIdEtapa(int idEtapa) {
        this.idEtapa = idEtapa;
    }
    public String getDescripcionEtapa() {
        return this.descripcionEtapa;
    }
    
    public void setDescripcionEtapa(String descripcionEtapa) {
        this.descripcionEtapa = descripcionEtapa;
    }
    public Set getTblSolicituds() {
        return this.tblSolicituds;
    }
    
    public void setTblSolicituds(Set tblSolicituds) {
        this.tblSolicituds = tblSolicituds;
    }




}


