package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TblEstado generated by hbm2java
 */
public class TblEstado  implements java.io.Serializable {


     private int idEstado;
     private String descripcionEstado;
     private Set tblSolicituds = new HashSet(0);

    public TblEstado() {
    }

	
    public TblEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public TblEstado(int idEstado, String descripcionEstado, Set tblSolicituds) {
       this.idEstado = idEstado;
       this.descripcionEstado = descripcionEstado;
       this.tblSolicituds = tblSolicituds;
    }
   
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public String getDescripcionEstado() {
        return this.descripcionEstado;
    }
    
    public void setDescripcionEstado(String descripcionEstado) {
        this.descripcionEstado = descripcionEstado;
    }
    public Set getTblSolicituds() {
        return this.tblSolicituds;
    }
    
    public void setTblSolicituds(Set tblSolicituds) {
        this.tblSolicituds = tblSolicituds;
    }




}


