package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblEtapa generated by hbm2java
 */
public class TblEtapa  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_etapa") 
     private Long idEtapa;
     private String descripcionEtapa;
     private Set tblSolicituds = new HashSet(0);

    public TblEtapa() {
    }

	
    public TblEtapa(Long idEtapa) {
        this.idEtapa = idEtapa;
    }
    public TblEtapa(Long idEtapa, String descripcionEtapa, Set tblSolicituds) {
       this.idEtapa = idEtapa;
       this.descripcionEtapa = descripcionEtapa;
       this.tblSolicituds = tblSolicituds;
    }
   
    public Long getIdEtapa() {
        return this.idEtapa;
    }
    
    public void setIdEtapa(Long idEtapa) {
        this.idEtapa = idEtapa;
    }
    public String getDescripcionEtapa() {
        return this.descripcionEtapa;
    }
    
    public void setDescripcionEtapa(String descripcionEtapa) {
        this.descripcionEtapa = descripcionEtapa;
    }
    public Set getTblSolicituds() {
        return this.tblSolicituds;
    }
    
    public void setTblSolicituds(Set tblSolicituds) {
        this.tblSolicituds = tblSolicituds;
    }




}


