package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblEstadoProduccion generated by hbm2java
 */
public class TblEstadoProduccion  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_estado_produccion")   
     private Long idEstadoProduccion;
     private String descripcionEstado;
     private Set tblCultivos = new HashSet(0);

    public TblEstadoProduccion() {
    }

	
    public TblEstadoProduccion(Long idEstadoProduccion) {
        this.idEstadoProduccion = idEstadoProduccion;
    }
    public TblEstadoProduccion(Long idEstadoProduccion, String descripcionEstado, Set tblCultivos) {
       this.idEstadoProduccion = idEstadoProduccion;
       this.descripcionEstado = descripcionEstado;
       this.tblCultivos = tblCultivos;
    }
   
    public Long getIdEstadoProduccion() {
        return this.idEstadoProduccion;
    }
    
    public void setIdEstadoProduccion(Long idEstadoProduccion) {
        this.idEstadoProduccion = idEstadoProduccion;
    }
    public String getDescripcionEstado() {
        return this.descripcionEstado;
    }
    
    public void setDescripcionEstado(String descripcionEstado) {
        this.descripcionEstado = descripcionEstado;
    }
    public Set getTblCultivos() {
        return this.tblCultivos;
    }
    
    public void setTblCultivos(Set tblCultivos) {
        this.tblCultivos = tblCultivos;
    }




}


