package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblEstado generated by hbm2java
 */
public class TblEstado  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_estado") 
     private Long idEstado;
     private String descripcionEstado;
     private Set tblSolicituds = new HashSet(0);

    public TblEstado() {
    }

	
    public TblEstado(Long idEstado) {
        this.idEstado = idEstado;
    }
    public TblEstado(Long idEstado, String descripcionEstado, Set tblSolicituds) {
       this.idEstado = idEstado;
       this.descripcionEstado = descripcionEstado;
       this.tblSolicituds = tblSolicituds;
    }
   
    public Long getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Long idEstado) {
        this.idEstado = idEstado;
    }
    public String getDescripcionEstado() {
        return this.descripcionEstado;
    }
    
    public void setDescripcionEstado(String descripcionEstado) {
        this.descripcionEstado = descripcionEstado;
    }
    public Set getTblSolicituds() {
        return this.tblSolicituds;
    }
    
    public void setTblSolicituds(Set tblSolicituds) {
        this.tblSolicituds = tblSolicituds;
    }




}


