package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblFunciones generated by hbm2java
 */
public class TblFunciones implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_funcion")
    private Long idFuncion;
    private String nombreFuncion;
    private Set tblFuncionRols = new HashSet(0);

    public TblFunciones() {
    }

    public TblFunciones(Long idFuncion) {
        this.idFuncion = idFuncion;
    }

    public TblFunciones(Long idFuncion, String nombreFuncion, Set tblFuncionRols) {
        this.idFuncion = idFuncion;
        this.nombreFuncion = nombreFuncion;
        this.tblFuncionRols = tblFuncionRols;
    }

    public Long getIdFuncion() {
        return this.idFuncion;
    }

    public void setIdFuncion(Long idFuncion) {
        this.idFuncion = idFuncion;
    }

    public String getNombreFuncion() {
        return this.nombreFuncion;
    }

    public void setNombreFuncion(String nombreFuncion) {
        this.nombreFuncion = nombreFuncion;
    }

    public Set getTblFuncionRols() {
        return this.tblFuncionRols;
    }

    public void setTblFuncionRols(Set tblFuncionRols) {
        this.tblFuncionRols = tblFuncionRols;
    }
}
