package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * TblFuncionRol generated by hbm2java
 */
public class TblFuncionRol  implements java.io.Serializable {

    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name="id_funcion_rol")
     private Long idFuncionRol;
     private TblFunciones tblFunciones;
     private TblRol tblRol;

    public TblFuncionRol() {
    }

	
    public TblFuncionRol(Long idFuncionRol) {
        this.idFuncionRol = idFuncionRol;
    }
    public TblFuncionRol(Long idFuncionRol, TblFunciones tblFunciones, TblRol tblRol) {
       this.idFuncionRol = idFuncionRol;
       this.tblFunciones = tblFunciones;
       this.tblRol = tblRol;
    }
   
    public Long getIdFuncionRol() {
        return this.idFuncionRol;
    }
    
    public void setIdFuncionRol(Long idFuncionRol) {
        this.idFuncionRol = idFuncionRol;
    }
    public TblFunciones getTblFunciones() {
        return this.tblFunciones;
    }
    
    public void setTblFunciones(TblFunciones tblFunciones) {
        this.tblFunciones = tblFunciones;
    }
    public TblRol getTblRol() {
        return this.tblRol;
    }
    
    public void setTblRol(TblRol tblRol) {
        this.tblRol = tblRol;
    }




}


