package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA



/**
 * TblImagen generated by hbm2java
 */
public class TblImagen  implements java.io.Serializable {


     private int idImagen;
     private TblSolicitud tblSolicitud;
     private String nombreImagen;
     private String pathImagen;

    public TblImagen() {
    }

	
    public TblImagen(int idImagen) {
        this.idImagen = idImagen;
    }
    public TblImagen(int idImagen, TblSolicitud tblSolicitud, String nombreImagen, String pathImagen) {
       this.idImagen = idImagen;
       this.tblSolicitud = tblSolicitud;
       this.nombreImagen = nombreImagen;
       this.pathImagen = pathImagen;
    }
   
    public int getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(int idImagen) {
        this.idImagen = idImagen;
    }
    public TblSolicitud getTblSolicitud() {
        return this.tblSolicitud;
    }
    
    public void setTblSolicitud(TblSolicitud tblSolicitud) {
        this.tblSolicitud = tblSolicitud;
    }
    public String getNombreImagen() {
        return this.nombreImagen;
    }
    
    public void setNombreImagen(String nombreImagen) {
        this.nombreImagen = nombreImagen;
    }
    public String getPathImagen() {
        return this.pathImagen;
    }
    
    public void setPathImagen(String pathImagen) {
        this.pathImagen = pathImagen;
    }




}


