package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * TblImagen generated by hbm2java
 */
public class TblImagen  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_imagen") 
     private Long idImagen;
     private TblSolicitud tblSolicitud;
     private String nombreImagen;
     private String pathImagen;

    public TblImagen() {
    }

	
    public TblImagen(Long idImagen) {
        this.idImagen = idImagen;
    }
    public TblImagen(Long idImagen, TblSolicitud tblSolicitud, String nombreImagen, String pathImagen) {
       this.idImagen = idImagen;
       this.tblSolicitud = tblSolicitud;
       this.nombreImagen = nombreImagen;
       this.pathImagen = pathImagen;
    }
   
    public Long getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(Long idImagen) {
        this.idImagen = idImagen;
    }
    public TblSolicitud getTblSolicitud() {
        return this.tblSolicitud;
    }
    
    public void setTblSolicitud(TblSolicitud tblSolicitud) {
        this.tblSolicitud = tblSolicitud;
    }
    public String getNombreImagen() {
        return this.nombreImagen;
    }
    
    public void setNombreImagen(String nombreImagen) {
        this.nombreImagen = nombreImagen;
    }
    public String getPathImagen() {
        return this.pathImagen;
    }
    
    public void setPathImagen(String pathImagen) {
        this.pathImagen = pathImagen;
    }




}


