package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TblPatologia generated by hbm2java
 */
public class TblPatologia  implements java.io.Serializable {


     private int idPatologia;
     private String descripcionPatologia;
     private String observacionesPatologia;
     private Set tblSolicituds = new HashSet(0);
     private Set tblSintomaPatologias = new HashSet(0);

    public TblPatologia() {
    }

	
    public TblPatologia(int idPatologia) {
        this.idPatologia = idPatologia;
    }
    public TblPatologia(int idPatologia, String descripcionPatologia, String observacionesPatologia, Set tblSolicituds, Set tblSintomaPatologias) {
       this.idPatologia = idPatologia;
       this.descripcionPatologia = descripcionPatologia;
       this.observacionesPatologia = observacionesPatologia;
       this.tblSolicituds = tblSolicituds;
       this.tblSintomaPatologias = tblSintomaPatologias;
    }
   
    public int getIdPatologia() {
        return this.idPatologia;
    }
    
    public void setIdPatologia(int idPatologia) {
        this.idPatologia = idPatologia;
    }
    public String getDescripcionPatologia() {
        return this.descripcionPatologia;
    }
    
    public void setDescripcionPatologia(String descripcionPatologia) {
        this.descripcionPatologia = descripcionPatologia;
    }
    public String getObservacionesPatologia() {
        return this.observacionesPatologia;
    }
    
    public void setObservacionesPatologia(String observacionesPatologia) {
        this.observacionesPatologia = observacionesPatologia;
    }
    public Set getTblSolicituds() {
        return this.tblSolicituds;
    }
    
    public void setTblSolicituds(Set tblSolicituds) {
        this.tblSolicituds = tblSolicituds;
    }
    public Set getTblSintomaPatologias() {
        return this.tblSintomaPatologias;
    }
    
    public void setTblSintomaPatologias(Set tblSintomaPatologias) {
        this.tblSintomaPatologias = tblSintomaPatologias;
    }




}


