package com.siscacao.model;
// Generated 10/08/2014 12:03:46 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * TblPushDevice generated by hbm2java
 */
public class TblPushDevice  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "push_device_id") 
     private Long pushDeviceId;
     private String numeroDocumento;
     private String deviceId;

    public TblPushDevice() {
    }

	
    public TblPushDevice(Long pushDeviceId) {
        this.pushDeviceId = pushDeviceId;
    }
    public TblPushDevice(Long pushDeviceId, String numeroDocumento, String deviceId) {
       this.pushDeviceId = pushDeviceId;
       this.numeroDocumento = numeroDocumento;
       this.deviceId = deviceId;
    }
   
    public Long getPushDeviceId() {
        return this.pushDeviceId;
    }
    
    public void setPushDeviceId(Long pushDeviceId) {
        this.pushDeviceId = pushDeviceId;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

}


