package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * TblRol generated by hbm2java
 */
public class TblRol  implements java.io.Serializable {

    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name="id_rol")
     private Long idRol;
     private String nombreRol;
     private Date fechaModificacion;
     private String descripcion;
     private Set tblFuncionRols = new HashSet(0);
     private Set tblUsuarioRols = new HashSet(0);

    public TblRol() {
    }

	
    public TblRol(Long idRol) {
        this.idRol = idRol;
    }
    public TblRol(Long idRol, String nombreRol, Date fechaModificacion, String descripcion, Set tblFuncionRols, Set tblUsuarioRols) {
       this.idRol = idRol;
       this.nombreRol = nombreRol;
       this.fechaModificacion = fechaModificacion;
       this.descripcion = descripcion;
       this.tblFuncionRols = tblFuncionRols;
       this.tblUsuarioRols = tblUsuarioRols;
    }
   
    public Long getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Long idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTblFuncionRols() {
        return this.tblFuncionRols;
    }
    
    public void setTblFuncionRols(Set tblFuncionRols) {
        this.tblFuncionRols = tblFuncionRols;
    }
    public Set getTblUsuarioRols() {
        return this.tblUsuarioRols;
    }
    
    public void setTblUsuarioRols(Set tblUsuarioRols) {
        this.tblUsuarioRols = tblUsuarioRols;
    }




}


