package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TblSintoma generated by hbm2java
 */
public class TblSintoma  implements java.io.Serializable {


     private int idSintoma;
     private String descripcionSintoma;
     private Set tblSintomaPatologias = new HashSet(0);

    public TblSintoma() {
    }

	
    public TblSintoma(int idSintoma) {
        this.idSintoma = idSintoma;
    }
    public TblSintoma(int idSintoma, String descripcionSintoma, Set tblSintomaPatologias) {
       this.idSintoma = idSintoma;
       this.descripcionSintoma = descripcionSintoma;
       this.tblSintomaPatologias = tblSintomaPatologias;
    }
   
    public int getIdSintoma() {
        return this.idSintoma;
    }
    
    public void setIdSintoma(int idSintoma) {
        this.idSintoma = idSintoma;
    }
    public String getDescripcionSintoma() {
        return this.descripcionSintoma;
    }
    
    public void setDescripcionSintoma(String descripcionSintoma) {
        this.descripcionSintoma = descripcionSintoma;
    }
    public Set getTblSintomaPatologias() {
        return this.tblSintomaPatologias;
    }
    
    public void setTblSintomaPatologias(Set tblSintomaPatologias) {
        this.tblSintomaPatologias = tblSintomaPatologias;
    }




}


