package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblSintoma generated by hbm2java
 */
public class TblSintoma  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_sintoma") 
     private Long idSintoma;
     private String descripcionSintoma;
     private Set tblSintomaPatologias = new HashSet(0);

    public TblSintoma() {
    }

	
    public TblSintoma(Long idSintoma) {
        this.idSintoma = idSintoma;
    }
    public TblSintoma(Long idSintoma, String descripcionSintoma, Set tblSintomaPatologias) {
       this.idSintoma = idSintoma;
       this.descripcionSintoma = descripcionSintoma;
       this.tblSintomaPatologias = tblSintomaPatologias;
    }
   
    public Long getIdSintoma() {
        return this.idSintoma;
    }
    
    public void setIdSintoma(Long idSintoma) {
        this.idSintoma = idSintoma;
    }
    public String getDescripcionSintoma() {
        return this.descripcionSintoma;
    }
    
    public void setDescripcionSintoma(String descripcionSintoma) {
        this.descripcionSintoma = descripcionSintoma;
    }
    public Set getTblSintomaPatologias() {
        return this.tblSintomaPatologias;
    }
    
    public void setTblSintomaPatologias(Set tblSintomaPatologias) {
        this.tblSintomaPatologias = tblSintomaPatologias;
    }




}


