package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * TblSintomaPatologia generated by hbm2java
 */
public class TblSintomaPatologia  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_sintoma_patologia") 
     private Long idSintomaPatologia;
     private TblSintoma tblSintoma;
     private TblPatologia tblPatologia;

    public TblSintomaPatologia() {
    }

	
    public TblSintomaPatologia(Long idSintomaPatologia) {
        this.idSintomaPatologia = idSintomaPatologia;
    }
    public TblSintomaPatologia(Long idSintomaPatologia, TblSintoma tblSintoma, TblPatologia tblPatologia) {
       this.idSintomaPatologia = idSintomaPatologia;
       this.tblSintoma = tblSintoma;
       this.tblPatologia = tblPatologia;
    }
   
    public Long getIdSintomaPatologia() {
        return this.idSintomaPatologia;
    }
    
    public void setIdSintomaPatologia(Long idSintomaPatologia) {
        this.idSintomaPatologia = idSintomaPatologia;
    }
    public TblSintoma getTblSintoma() {
        return this.tblSintoma;
    }
    
    public void setTblSintoma(TblSintoma tblSintoma) {
        this.tblSintoma = tblSintoma;
    }
    public TblPatologia getTblPatologia() {
        return this.tblPatologia;
    }
    
    public void setTblPatologia(TblPatologia tblPatologia) {
        this.tblPatologia = tblPatologia;
    }




}


