package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblTipoDocumento generated by hbm2java
 */
public class TblTipoDocumento  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_tipo_documento")
     private Long idTipoDocumento;
     private String descripcionTipo;
     private String nombreTipo;
     private Set tblSolicitantes = new HashSet(0);
     private Set tblDetalleUsuarios = new HashSet(0);

    public TblTipoDocumento() {
    }

	
    public TblTipoDocumento(Long idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public TblTipoDocumento(Long idTipoDocumento, String descripcionTipo, String nombreTipo, Set tblSolicitantes, Set tblDetalleUsuarios) {
       this.idTipoDocumento = idTipoDocumento;
       this.descripcionTipo = descripcionTipo;
       this.nombreTipo = nombreTipo;
       this.tblSolicitantes = tblSolicitantes;
       this.tblDetalleUsuarios = tblDetalleUsuarios;
    }
   
    public Long getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(Long idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public String getDescripcionTipo() {
        return this.descripcionTipo;
    }
    
    public void setDescripcionTipo(String descripcionTipo) {
        this.descripcionTipo = descripcionTipo;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public Set getTblSolicitantes() {
        return this.tblSolicitantes;
    }
    
    public void setTblSolicitantes(Set tblSolicitantes) {
        this.tblSolicitantes = tblSolicitantes;
    }
    public Set getTblDetalleUsuarios() {
        return this.tblDetalleUsuarios;
    }
    
    public void setTblDetalleUsuarios(Set tblDetalleUsuarios) {
        this.tblDetalleUsuarios = tblDetalleUsuarios;
    }




}


