package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblTecnicaCultivo generated by hbm2java
 */
public class TblTecnicaCultivo  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_tecnica")   
     private Long idTecnica;
     private String nombreTecnica;
     private Set tblCultivos = new HashSet(0);

    public TblTecnicaCultivo() {
    }

	
    public TblTecnicaCultivo(Long idTecnica) {
        this.idTecnica = idTecnica;
    }
    public TblTecnicaCultivo(Long idTecnica, String nombreTecnica, Set tblCultivos) {
       this.idTecnica = idTecnica;
       this.nombreTecnica = nombreTecnica;
       this.tblCultivos = tblCultivos;
    }
   
    public Long getIdTecnica() {
        return this.idTecnica;
    }
    
    public void setIdTecnica(Long idTecnica) {
        this.idTecnica = idTecnica;
    }
    public String getNombreTecnica() {
        return this.nombreTecnica;
    }
    
    public void setNombreTecnica(String nombreTecnica) {
        this.nombreTecnica = nombreTecnica;
    }
    public Set getTblCultivos() {
        return this.tblCultivos;
    }
    
    public void setTblCultivos(Set tblCultivos) {
        this.tblCultivos = tblCultivos;
    }




}


