package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblTipoContacto generated by hbm2java
 */
public class TblTipoContacto  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_tipo_contacto")
     private Long idTipoContacto;
     private String descripcion;
     private String nombreTipo;
     private Set tblContactos = new HashSet(0);

    public TblTipoContacto() {
    }

	
    public TblTipoContacto(Long idTipoContacto) {
        this.idTipoContacto = idTipoContacto;
    }
    public TblTipoContacto(Long idTipoContacto, String descripcion, String nombreTipo, Set tblContactos) {
       this.idTipoContacto = idTipoContacto;
       this.descripcion = descripcion;
       this.nombreTipo = nombreTipo;
       this.tblContactos = tblContactos;
    }
   
    public Long getIdTipoContacto() {
        return this.idTipoContacto;
    }
    
    public void setIdTipoContacto(Long idTipoContacto) {
        this.idTipoContacto = idTipoContacto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public Set getTblContactos() {
        return this.tblContactos;
    }
    
    public void setTblContactos(Set tblContactos) {
        this.tblContactos = tblContactos;
    }




}


