package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblTipoSolicitud generated by hbm2java
 */
public class TblTipoSolicitud  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_tipo_solicitud") 
     private Long idTipoSolicitud;
     private String nombreTipo;
     private Set tblSolicituds = new HashSet(0);

    public TblTipoSolicitud() {
    }

	
    public TblTipoSolicitud(Long idTipoSolicitud) {
        this.idTipoSolicitud = idTipoSolicitud;
    }
    public TblTipoSolicitud(Long idTipoSolicitud, String nombreTipo, Set tblSolicituds) {
       this.idTipoSolicitud = idTipoSolicitud;
       this.nombreTipo = nombreTipo;
       this.tblSolicituds = tblSolicituds;
    }
   
    public Long getIdTipoSolicitud() {
        return this.idTipoSolicitud;
    }
    
    public void setIdTipoSolicitud(Long idTipoSolicitud) {
        this.idTipoSolicitud = idTipoSolicitud;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public Set getTblSolicituds() {
        return this.tblSolicituds;
    }
    
    public void setTblSolicituds(Set tblSolicituds) {
        this.tblSolicituds = tblSolicituds;
    }




}


