package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;




/**
 * TblUsuarioRol generated by hbm2java
 */
public class TblUsuarioRol  implements java.io.Serializable {

    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name="id_rol")
     private Long idUsuarioRol;
     private TblRol tblRol;
     private TblUsuario tblUsuario;

    public TblUsuarioRol() {
    }

	
    public TblUsuarioRol(Long idUsuarioRol) {
        this.idUsuarioRol = idUsuarioRol;
    }
    public TblUsuarioRol(Long idUsuarioRol, TblRol tblRol, TblUsuario tblUsuario) {
       this.idUsuarioRol = idUsuarioRol;
       this.tblRol = tblRol;
       this.tblUsuario = tblUsuario;
    }
   
    public Long getIdUsuarioRol() {
        return this.idUsuarioRol;
    }
    
    public void setIdUsuarioRol(Long idUsuarioRol) {
        this.idUsuarioRol = idUsuarioRol;
    }
    public TblRol getTblRol() {
        return this.tblRol;
    }
    
    public void setTblRol(TblRol tblRol) {
        this.tblRol = tblRol;
    }
    public TblUsuario getTblUsuario() {
        return this.tblUsuario;
    }
    
    public void setTblUsuario(TblUsuario tblUsuario) {
        this.tblUsuario = tblUsuario;
    }




}


