package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
/**
 * TblUsuario generated by hbm2java
 */
public class TblUsuario  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_usuario")
     private Long idUsuario;
     private String nombreUsuario;
     private Date fechaUltimaActividad;
     private String cuenta;
     private String contrasena;
     private Date fechaRegistro;
     private Set tblAsignacionSolicituds = new HashSet(0);
     private Set tblUsuarioRols = new HashSet(0);
     private Set tblDetalleUsuarios = new HashSet(0);
     //Adicional
     String Rol;

    public TblUsuario() {
    }

	
    public TblUsuario(Long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TblUsuario(Long idUsuario, String nombreUsuario, Date fechaUltimaActividad, String cuenta, String contrasena, Date fechaRegistro, Set tblAsignacionSolicituds, Set tblUsuarioRols, Set tblDetalleUsuarios) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.fechaUltimaActividad = fechaUltimaActividad;
       this.cuenta = cuenta;
       this.contrasena = contrasena;
       this.fechaRegistro = fechaRegistro;
       this.tblAsignacionSolicituds = tblAsignacionSolicituds;
       this.tblUsuarioRols = tblUsuarioRols;
       this.tblDetalleUsuarios = tblDetalleUsuarios;
    }
   
    public Long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public Date getFechaUltimaActividad() {
        return this.fechaUltimaActividad;
    }
    
    public void setFechaUltimaActividad(Date fechaUltimaActividad) {
        this.fechaUltimaActividad = fechaUltimaActividad;
    }
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getTblAsignacionSolicituds() {
        return this.tblAsignacionSolicituds;
    }
    
    public void setTblAsignacionSolicituds(Set tblAsignacionSolicituds) {
        this.tblAsignacionSolicituds = tblAsignacionSolicituds;
    }
    public Set getTblUsuarioRols() {
        setInmediateRol();
        return this.tblUsuarioRols;
    }
    
    public void setTblUsuarioRols(Set tblUsuarioRols) {
        this.tblUsuarioRols = tblUsuarioRols;
    }
    public Set getTblDetalleUsuarios() {
        return this.tblDetalleUsuarios;
    }
    
    public void setTblDetalleUsuarios(Set tblDetalleUsuarios) {
        this.tblDetalleUsuarios = tblDetalleUsuarios;
    }

    public void setIdUsuario(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    //adicional
    public String getRol() {
        return Rol;
    }

    public void setRol(String Rol) {
        this.Rol = Rol;
    }

    private void setInmediateRol() {
        String rol = "";
      for (Iterator it = tblUsuarioRols.iterator(); it.hasNext();) {
          TblUsuarioRol x = (TblUsuarioRol) it.next();
          rol = x.getTblRol().getNombreRol();
          setRol(rol);
      }
    }
    


}


