package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * TblVariedad generated by hbm2java
 */
public class TblVariedad  implements java.io.Serializable {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Basic(optional = false)
     @Column(name = "id_variedad")
     private Long idVariedad;
     private String nombreVariedad;
     private Set tblCultivos = new HashSet(0);

    public TblVariedad() {
    }

	
    public TblVariedad(Long idVariedad) {
        this.idVariedad = idVariedad;
    }
    public TblVariedad(Long idVariedad, String nombreVariedad, Set tblCultivos) {
       this.idVariedad = idVariedad;
       this.nombreVariedad = nombreVariedad;
       this.tblCultivos = tblCultivos;
    }
   
    public Long getIdVariedad() {
        return this.idVariedad;
    }
    
    public void setIdVariedad(Long idVariedad) {
        this.idVariedad = idVariedad;
    }
    public String getNombreVariedad() {
        return this.nombreVariedad;
    }
    
    public void setNombreVariedad(String nombreVariedad) {
        this.nombreVariedad = nombreVariedad;
    }
    public Set getTblCultivos() {
        return this.tblCultivos;
    }
    
    public void setTblCultivos(Set tblCultivos) {
        this.tblCultivos = tblCultivos;
    }




}


