package com.siscacao.model;
// Generated 20/10/2013 04:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TblVereda generated by hbm2java
 */
public class TblVereda  implements java.io.Serializable {


     private int idVereda;
     private TblDepartamento tblDepartamento;
     private String nombreVereda;
     private Set tblSolicituds = new HashSet(0);

    public TblVereda() {
    }

	
    public TblVereda(int idVereda) {
        this.idVereda = idVereda;
    }
    public TblVereda(int idVereda, TblDepartamento tblDepartamento, String nombreVereda, Set tblSolicituds) {
       this.idVereda = idVereda;
       this.tblDepartamento = tblDepartamento;
       this.nombreVereda = nombreVereda;
       this.tblSolicituds = tblSolicituds;
    }
   
    public int getIdVereda() {
        return this.idVereda;
    }
    
    public void setIdVereda(int idVereda) {
        this.idVereda = idVereda;
    }
    public TblDepartamento getTblDepartamento() {
        return this.tblDepartamento;
    }
    
    public void setTblDepartamento(TblDepartamento tblDepartamento) {
        this.tblDepartamento = tblDepartamento;
    }
    public String getNombreVereda() {
        return this.nombreVereda;
    }
    
    public void setNombreVereda(String nombreVereda) {
        this.nombreVereda = nombreVereda;
    }
    public Set getTblSolicituds() {
        return this.tblSolicituds;
    }
    
    public void setTblSolicituds(Set tblSolicituds) {
        this.tblSolicituds = tblSolicituds;
    }




}


